version: '3'
services:
  postgres:
    container_name: postgres
    build: ./database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./muzyaka
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
