version: '3'
services:
  postgres:
    container_name: postgres
    build: ./database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./muzyaka
    depends_on:
      - postgres
    ports:
      - "8080:8080"
