version: '3'
services:
  db:
    container_name: db
    build: ./database
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./muzyaka
    depends_on:
      - db
    #    depends_on:
#      postgres:
#        condition: service_healthy
    ports:
      - "8080:8080"
