version: '3'
services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:16
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_PORT: 5432
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./muzyaka
    depends_on:
      - postgres
    #    depends_on:
#      postgres:
#        condition: service_healthy
    ports:
      - "8080:8080"
